apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-log-service
  namespace: kubenexus
  labels:
    app: audit-log-service
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audit-log-service
  template:
    metadata:
      labels:
        app: audit-log-service
        component: backend
    spec:
      imagePullSecrets:
      - name: kubenexus-registry-secret
      containers:
      - name: audit-log-service
        image: kubenexus/audit-log-service:latest
        ports:
        - containerPort: 8003
        env:
        - name: PORT
          value: "8003"
        envFrom:
        - configMapRef:
            name: kubenexus-config
        - secretRef:
            name: kubenexus-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: "512Mi"
            cpu: "300m"
          requests:
            memory: "256Mi"
            cpu: "150m"
---
apiVersion: v1
kind: Service
metadata:
  name: audit-log-service
  namespace: kubenexus
  labels:
    app: audit-log-service
    component: backend
spec:
  selector:
    app: audit-log-service
  ports:
  - port: 8003
    targetPort: 8003
  type: ClusterIP 