apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-manager-sa
  namespace: kubenexus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-manager-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-manager-role
subjects:
- kind: ServiceAccount
  name: cluster-manager-sa
  namespace: kubenexus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-manager-service
  namespace: kubenexus
  labels:
    app: cluster-manager-service
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cluster-manager-service
  template:
    metadata:
      labels:
        app: cluster-manager-service
        component: backend
    spec:
      serviceAccountName: cluster-manager-sa
      imagePullSecrets:
      - name: kubenexus-registry-secret
      containers:
      - name: cluster-manager-service
        image: kubenexus/cluster-manager-service:latest
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          value: "8002"
        envFrom:
        - configMapRef:
            name: kubenexus-config
        - secretRef:
            name: kubenexus-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-manager-service
  namespace: kubenexus
  labels:
    app: cluster-manager-service
    component: backend
spec:
  selector:
    app: cluster-manager-service
  ports:
  - port: 8002
    targetPort: 8002
  type: ClusterIP 