apiVersion: v1
kind: ConfigMap
metadata:
  name: kubenexus-config
  namespace: kubenexus
data:
  # Database Configuration
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "kubenexus"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:8001"
  CLUSTER_MANAGER_URL: "http://cluster-manager-service:8002"
  AUDIT_LOG_URL: "http://audit-log-service:8003"
  METRICS_URL: "http://metrics-service:8004"
  SRE_AGENT_URL: "http://sre-agent-service:8005"
  TERMINAL_URL: "http://terminal-service:8006"
  
  # Environment
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  
  # SRE Configuration
  SRE_ML_MODEL_PATH: "/models"
  SRE_ANALYSIS_INTERVAL: "300"
  SRE_ALERT_THRESHOLD: "0.8"
  
  # Security
  CORS_ORIGINS: "https://kubenexus.example.com"
  ALLOWED_HOSTS: "kubenexus.example.com,localhost"
  
  # Monitoring
  METRICS_RETENTION_DAYS: "30"
  AUDIT_RETENTION_DAYS: "90" 