apiVersion: v1
kind: Secret
metadata:
  name: kubenexus-secrets
  namespace: kubenexus
type: Opaque
data:
  # Base64 encoded secrets - Replace with actual values
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzcw==  # postgres_pass
  REDIS_PASSWORD: cmVkaXNfcGFzcw==  # redis_pass
  JWT_SECRET_KEY: Y2hhbmdlLW1lLXRvLWEtcmFuZG9tLWpzb24td2ViLXRva2VuLXNlY3JldA==  # change-me-to-a-random-json-web-token-secret
  ENCRYPTION_KEY: Y2hhbmdlLW1lLXRvLWEtcmFuZG9tLWVuY3J5cHRpb24ta2V5  # change-me-to-a-random-encryption-key
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzX3Bhc3NAcG9zdGdyZXMtc2VydmljZTo1NDMyL2t1YmVuZXh1cw==  # postgresql://postgres:postgres_pass@postgres-service:5432/kubenexus
  REDIS_URL: cmVkaXM6Ly86cmVkaXNfcGFzc0ByZWRpcy1zZXJ2aWNlOjYzNzkvMA==  # redis://:redis_pass@redis-service:6379/0
---
apiVersion: v1
kind: Secret
metadata:
  name: kubenexus-registry-secret
  namespace: kubenexus
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==  # Replace with actual registry credentials 